#https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=vsts&tabs=yaml

variables:
    year: $(Date:yyyy)
    month: $(Date:MM)
    day: $(Date:dd)
    uk: $(Date:yyyyMMdd)
    messagePush: $(Build.SourceVersionMessage)

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:


- job: FullTestOnLinux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self #skip checking out the default repository resource
      clean: true
  
    
    - script: |
        
        cd dockerize
        ls -l
        chmod 777 ./ci_test.bat 
        ./ci_test.bat

        docker image ls
        docker container ls
        cp -r -v ./jest-stare  $(Build.ArtifactStagingDirectory)/jest-stare/ 
    
      displayName: test DDD
    
    - task: PublishBuildArtifacts@1
      inputs:
         artifactName: Tests
      displayName: 'Publish Artifact: drop' 
    
    
